### ISSUE TITLE
Sensory Memory core

### ISSUE THREAD

**Issue by pulinagrawal** [CognitiveComputingResearchGroup/lidapy-framework#6]
I found that tensorflow has a pre-trained model for [Image Recognition](https://www.tensorflow.org/versions/r0.8/tutorials/image_recognition/index.html#usage-with-python-api) with a python API to it.

We might be able to use it directly without much hassle.

**Comment by skugele** [comment]
Cool.  This is definitely worth playing around with.  I know that a lack of a pre-trained model was the main reason we were thinking of using Caffe rather than Tensorflow.

I am curious about the title of this issue though.  I would like to better understand how you were thinking about integrating this with LIDA.  Tamas had previously suggested removing the top layers of a pre-trained CNN and using that as our feature detectors.  Is your plan similar?  Would this be both PAM and Sensory memory?

@pulinagrawal

**Comment by pulinagrawal** [comment]
According to LIDA model the top layer of such a CNN should be inside PAM. The lower layers would probably be called Sensory Memory. 

Now, I do not have an answer to your first question yet. And maybe this issue was better suited to flagship-project because CNN for vision is very specific use case for Sensory Memory. Sorry about that.

**Comment by skugele** [comment]
Pulin - based on your last comment from May 2016 I am closing this issue; however, I think it may be useful at some point in the future to add some domain specific functionality to lidapy if there is general interest.

If/when we get to that point we can open a related issue.  Could even be part of a good lidapy example agent.
